#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for XC maintenance mode
#
#  Portions Copyright (c) 2010-2012 Postgres-XC Development Group
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/pgxc/xc_watchdog
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = xc_watchdog.o

include $(top_srcdir)/src/backend/common.mk
